server:
  port: 0
spring:
  application:
    name: REVIEW-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:staynest_review_service}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
jwt:
  secret: ${JWT_SECRET}
booking-service:
  url: ${BOOKING_SERVICE_URL:http://BOOKING-SERVICE}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info
